//! The list of validators in `src/regex.rs`, each with the pattern it implements and the input
//! material used to test it.
//!
//! `pattern` is copied verbatim from the doc comment of the validator; `common/verify.rs` compiles
//! it with the `regex` crate and compares the result of the hand written validator against it.
//! `alphabet` and `samples` steer the input generation: every string over `alphabet` up to
//! `exhaustive_len` characters is tested, plus every single character edit of every sample. The
//! alphabet should contain the interesting characters of the pattern (and a few uninteresting
//! ones), the samples should cover the parts of the pattern that random short strings never reach.

#![allow(dead_code)]

use crate::candidates::Validator;

pub struct RegexCase {
    pub name: &'static str,
    pub pattern: &'static str,
    pub validate: Validator,
    pub alphabet: &'static str,
    pub exhaustive_len: usize,
    pub samples: &'static [&'static str],
}

pub static CASES: &[RegexCase] = &[
    RegexCase {
        name: "regex_1",
        pattern: r"^(0[xX][0-9a-fA-F]+)$",
        validate: crate::regex::validate_regex_1,
        alphabet: "0xXaF9g",
        exhaustive_len: 4,
        samples: &["0x1", "0X1F", "0x", "0X", "0", "x1", "0xg", "00x1", "0xAf09"],
    },
    RegexCase {
        name: "regex_2",
        pattern: r"^([1-9][0-9]*|0[xX][0-9a-fA-F]*|0[bB][0-1]+|0[0-7]*|UNSPECIFIED|UNKNOWN|BOOLEAN|PTR)$",
        validate: crate::regex::validate_regex_2,
        alphabet: "018xXbB9",
        exhaustive_len: 4,
        samples: &[
            "1",
            "0",
            "07",
            "08",
            "0x",
            "0xAF",
            "0b1",
            "0b",
            "UNSPECIFIED",
            "UNKNOWN",
            "BOOLEAN",
            "PTR",
            "1234567890",
        ],
    },
    RegexCase {
        name: "regex_3",
        pattern: r"^([1-9][0-9]*|0[xX][0-9a-fA-F]+|0[0-7]*|0[bB][0-1]+|ANY|ALL)$",
        validate: crate::regex::validate_regex_3,
        alphabet: "018xXbB9",
        exhaustive_len: 4,
        samples: &["1", "0", "07", "0x", "0xAF", "0b1", "ANY", "ALL", "AN", "ANYY"],
    },
    RegexCase {
        name: "regex_4",
        pattern: r"^([0-9]+|ANY)$",
        validate: crate::regex::validate_regex_4,
        alphabet: "09AN",
        exhaustive_len: 4,
        samples: &["0", "1234", "ANY", "any", "AN"],
    },
    RegexCase {
        name: "regex_5",
        pattern: r"^([0-9]+|STRING|ARRAY)$",
        validate: crate::regex::validate_regex_5,
        alphabet: "09SAR",
        exhaustive_len: 4,
        samples: &["0", "1234", "STRING", "ARRAY", "STRIN", "ARRAYS"],
    },
    RegexCase {
        name: "regex_6",
        pattern: r"^(0|1|true|false)$",
        validate: crate::regex::validate_regex_6,
        alphabet: "01tf",
        exhaustive_len: 4,
        samples: &["0", "1", "true", "false", "TRUE", "2"],
    },
    RegexCase {
        name: "regex_7",
        pattern: r"^([a-zA-Z_][a-zA-Z0-9_]*)$",
        validate: crate::regex::validate_regex_7,
        alphabet: "aZ0_-",
        exhaustive_len: 5,
        samples: &["a", "_", "_Text_1", "Text_0123456789_Text_0123456789_abc"],
    },
    RegexCase {
        name: "regex_8",
        pattern: r"^([a-zA-Z][a-zA-Z0-9_]*)$",
        validate: crate::regex::validate_regex_8,
        alphabet: "aZ0_-",
        exhaustive_len: 5,
        samples: &["a", "Text_0", "Text_0123456789_Text_0123456789_abc"],
    },
    RegexCase {
        name: "regex_9",
        pattern: r"^(([0-9]{4}-[0-9]{2}-[0-9]{2})(T[0-9]{2}:[0-9]{2}:[0-9]{2}(Z|([+\-][0-9]{2}:[0-9]{2})))?)$",
        validate: crate::regex::validate_regex_9,
        alphabet: "0-T:Z+9",
        exhaustive_len: 4,
        samples: &[
            "2023-01-02",
            "2023-01-02T03:04:05Z",
            "2023-01-02T03:04:05+06:07",
            "2023-01-02T03:04:05-06:07",
            "2023-01-02T03:04:05",
            "2023-01-02T03:04:05z",
            "9999-99-99",
        ],
    },
    RegexCase {
        name: "regex_10",
        pattern: r"^([a-zA-Z][a-zA-Z0-9-]*)$",
        validate: crate::regex::validate_regex_10,
        alphabet: "aZ0-_",
        exhaustive_len: 5,
        samples: &["a", "a-b-9", "a_b"],
    },
    RegexCase {
        name: "regex_11",
        pattern: r"^([0-9a-zA-Z_\-]+)$",
        validate: crate::regex::validate_regex_11,
        alphabet: "aZ0-_.",
        exhaustive_len: 5,
        samples: &["a", "0-_Z", "a.b"],
    },
    RegexCase {
        name: "regex_12",
        pattern: r"^(%[ \-+#]?[0-9]*(\.[0-9]+)?[bBdiouxXfeEgGcs])$",
        validate: crate::regex::validate_regex_12,
        alphabet: "%-+#. 09ds",
        exhaustive_len: 4,
        samples: &[
            "%d", "%s", "%b", "%B", "%i", "%o", "%u", "%x", "%X", "%f", "%e", "%E", "%g", "%G", "%c", "% 5.2f",
            "%-#10.3E", "%.0d", "%5d", "%a", "%12.34s", "%+d", "%#o", "% d",
        ],
    },
    RegexCase {
        name: "regex_13",
        pattern: r"^(0|[\+\-]?[1-9][0-9]*|0[xX][0-9a-fA-F]+|0[bB][0-1]+|0[0-7]+)$",
        validate: crate::regex::validate_regex_13,
        alphabet: "0+-1x9bB7",
        exhaustive_len: 4,
        samples: &["0", "+1", "-1", "-0", "017", "0x1F", "0b10", "+0x1", "1234567890", "08"],
    },
    RegexCase {
        name: "regex_14",
        pattern: concat!(
            r"^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.",
            r"(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|ANY)$"
        ),
        validate: crate::regex::validate_regex_14,
        alphabet: "0.1259A",
        exhaustive_len: 4,
        samples: &[
            "1.2.3.4",
            "255.255.255.255",
            "256.1.1.1",
            "0.0.0.0",
            "099.1.1.1",
            "199.249.250.255",
            "260.1.1.1",
            "1.2.3",
            "1.2.3.4.5",
            "ANY",
            "01.02.03.04",
            "000.000.000.000",
        ],
    },
    RegexCase {
        name: "regex_15",
        pattern: r"^([0-9A-Fa-f]{1,4}(:[0-9A-Fa-f]{1,4}){7,7}|ANY)$",
        validate: crate::regex::validate_regex_15,
        alphabet: "0:aF9A",
        exhaustive_len: 4,
        samples: &[
            "1:2:3:4:5:6:7:8",
            "aaaa:bbbb:cccc:dddd:eeee:ffff:0000:9999",
            "1:2:3:4:5:6:7",
            "1:2:3:4:5:6:7:8:9",
            "12345:2:3:4:5:6:7:8",
            "1::3:4:5:6:7:8",
            "ANY",
        ],
    },
    RegexCase {
        name: "regex_16",
        pattern: concat!(
            r"^((0[xX][0-9a-fA-F]+)|(0[0-7]+)|(0[bB][0-1]+)|(([+\-]?[1-9][0-9]+(\.[0-9]+)?|",
            r"[+\-]?[0-9](\.[0-9]+)?)([eE]([+\-]?)[0-9]+)?)|\.0|INF|-INF|NaN)$"
        ),
        validate: crate::regex::validate_regex_16,
        alphabet: "0.1e+-9xN",
        exhaustive_len: 4,
        samples: &[
            "INF",
            "-INF",
            "NaN",
            "+INF",
            "nan",
            ".0",
            ".5",
            "0x1F",
            "017",
            "0b101",
            "1.5e-3",
            "12",
            "1",
            "1.0",
            "0",
            "-1.5E+10",
            "10",
            "01",
            "09",
            "1e5",
            "1.",
            "1.2.3",
            "+5",
            "-0.0",
            "12345.6789e0",
        ],
    },
    RegexCase {
        name: "regex_17",
        pattern: r"^(([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2})$",
        validate: crate::regex::validate_regex_17,
        alphabet: "0:aF9",
        exhaustive_len: 4,
        samples: &[
            "00:11:22:33:44:55",
            "aa:bb:cc:dd:ee:ff",
            "AA:BB:CC:DD:EE:FF",
            "00:11:22:33:44:5",
            "00:11:22:33:44:555",
            "0:11:22:33:44:55",
            "00-11-22-33-44-55",
        ],
    },
    RegexCase {
        name: "regex_18",
        pattern: concat!(
            r"^([a-zA-Z_][a-zA-Z0-9_]*(\[([a-zA-Z_][a-zA-Z0-9_]*|[0-9]+)\])*",
            r"(\.[a-zA-Z_][a-zA-Z0-9_]*(\[([a-zA-Z_][a-zA-Z0-9_]*|[0-9]+)\])*)*)$"
        ),
        validate: crate::regex::validate_regex_18,
        alphabet: "a0_[].",
        exhaustive_len: 5,
        samples: &[
            "a",
            "_x9",
            "a[0]",
            "a[b]",
            "a[12][x]",
            "a.b",
            "a[0].b[c].d",
            "a[]",
            "a[0",
            "a.",
            ".a",
            "a[0]b",
            "9a",
            "a[b0]",
            "a[0b]",
        ],
    },
    RegexCase {
        name: "regex_19",
        pattern: r"^([A-Z][a-zA-Z0-9_]*)$",
        validate: crate::regex::validate_regex_19,
        alphabet: "Aa0_-",
        exhaustive_len: 5,
        samples: &["A", "Abc_0", "aBC"],
    },
    RegexCase {
        name: "regex_20",
        pattern: r"^([1-9][0-9]*)$",
        validate: crate::regex::validate_regex_20,
        alphabet: "019-",
        exhaustive_len: 5,
        samples: &["1", "10", "0", "01", "1234567890"],
    },
    RegexCase {
        name: "regex_21",
        pattern: r"^(0|[\+]?[1-9][0-9]*|0[xX][0-9a-fA-F]+|0[bB][0-1]+|0[0-7]+)$",
        validate: crate::regex::validate_regex_21,
        alphabet: "0+-1x9bB7",
        exhaustive_len: 4,
        samples: &["0", "+1", "-1", "017", "0x1F", "0b10", "1234567890", "08"],
    },
    RegexCase {
        name: "regex_22",
        pattern: r"^([a-zA-Z]([a-zA-Z0-9]|_[a-zA-Z0-9])*_?)$",
        validate: crate::regex::validate_regex_22,
        alphabet: "a0_Z9",
        exhaustive_len: 5,
        samples: &["a", "a_", "a_b", "a__b", "a__", "_a", "aZ9_0_"],
    },
    RegexCase {
        name: "regex_23",
        pattern: r"^(-?([0-9]+|MAX-TEXT-SIZE|ARRAY-SIZE))$",
        validate: crate::regex::validate_regex_23,
        alphabet: "-09MA",
        exhaustive_len: 4,
        samples: &[
            "0",
            "-123",
            "MAX-TEXT-SIZE",
            "-MAX-TEXT-SIZE",
            "ARRAY-SIZE",
            "-ARRAY-SIZE",
            "MAX-TEXT-SIZ",
            "--1",
        ],
    },
    RegexCase {
        name: "regex_24",
        pattern: r"^(/?[a-zA-Z][a-zA-Z0-9_]{0,127}(/[a-zA-Z][a-zA-Z0-9_]{0,127})*)$",
        validate: crate::regex::validate_regex_24,
        alphabet: "/aZ0_",
        exhaustive_len: 5,
        samples: &[
            "/a",
            "a",
            "/pkg/element",
            "pkg/element",
            "/pkg//element",
            "/pkg/element/",
        ],
    },
    RegexCase {
        name: "regex_25",
        pattern: r"^([0-9]+\.[0-9]+\.[0-9]+([\._;].*)?)$",
        validate: crate::regex::validate_regex_25,
        alphabet: "0.9;_x",
        exhaustive_len: 5,
        samples: &[
            "1.2.3",
            "10.20.30",
            "1.2.3.anything here",
            "1.2.3;x",
            "1.2.3_y",
            "1.2.3x",
            "1.2",
            "1.2.3.",
            "1.2.3;",
            "1.2.3_",
        ],
    },
    RegexCase {
        name: "regex_26",
        pattern: concat!(
            r"^((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-((0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)",
            r"(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?)$"
        ),
        validate: crate::regex::validate_regex_26,
        alphabet: "0.1-+a9",
        exhaustive_len: 5,
        samples: &[
            "1.2.3",
            "0.0.0",
            "01.2.3",
            "1.2.3-alpha",
            "1.2.3-alpha.1",
            "1.2.3-0.3.7",
            "1.2.3-x.7.z.92",
            "1.2.3+build",
            "1.2.3+build.1",
            "1.2.3-beta+exp.sha.5114f85",
            "1.2.3-",
            "1.2.3+",
            "1.2.3-01",
            "1.2.3-0a",
            "1.2.3-a..b",
            "1.2.3+a..b",
            "1.2",
            "1.2.3.4",
        ],
    },
    RegexCase {
        name: "regex_27",
        pattern: r"^([0-1])$",
        validate: crate::regex::validate_regex_27,
        alphabet: "012",
        exhaustive_len: 3,
        samples: &["0", "1", "2", "01"],
    },
    RegexCase {
        name: "regex_28",
        pattern: r"^((-?[a-zA-Z_]+)(( )+-?[a-zA-Z_]+)*)$",
        validate: crate::regex::validate_regex_28,
        alphabet: "a -_Z",
        exhaustive_len: 5,
        samples: &[
            "abc", "-abc", "a b", "a  b", "-a -b  c", "a-b", " a", "a ", "a - b", "_a b_", "-", "--a",
        ],
    },
];
